# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'Openshif Online'
    cmd: 'oc new-app https://github.com/cronaldo/django-ex.git -l -name=myapp-django'

#- task: oc-cmd@2
#  inputs:
#    connectionType: 'OpenShift Connection Service'
#    openshiftService: 'Openshif Online'
#    cmd: 'oc start-build  --follow'
#- task: oc-cmd@2
#  inputs:
#    connectionType: 'OpenShift Connection Service'
#    openshiftService: 'Openshif Online'
#    cmd: 'oc start-build nodejs-ex --follow'
#- task: oc-cmd@2
#  inputs:
#    connectionType: 'OpenShift Connection Service'
#    openshiftService: 'Openshif Online'
#    cmd: 'oc status'